[package]
name = "lua-runner"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.228", features = ["derive"] }
mlua = { version = "0.11.4", features = ["lua54", "vendored"] }
